models:
  - name: "LLaMA 3 8B Instruct Q5_K_M"
    path_to_gguf: "Meta-Llama-3-8B-Instruct-Q5_K_M.gguf"
    context_size: 8196
  - name: "LLaMA 3 70B Instruct Q5_K_M"
    path_to_gguf: "Meta-Llama-3-70B-Instruct.Q5_K_M.gguf"
    context_size: 8196